2018-04-16 08:59:58,051 ERROR: Exception on /login [GET] [in C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Albert\Documents\GitHub\microblog\app\routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Albert\Documents\GitHub\microblog\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Albert\Documents\GitHub\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\Albert\Documents\GitHub\microblog\app\templates\base.html", line 21, in block "navbar"
    <li><a href="{{ url_for('index') }}">{{ _('Home') }}</a></li>
jinja2.exceptions.UndefinedError: '_' is undefined
2018-04-19 00:43:34,211 INFO: Microblog startup [in C:\Users\Albert\Documents\GitHub\microblog\app\__init__.py:48]
2018-04-19 00:43:39,128 ERROR: Exception on /login [GET] [in C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Albert\Documents\GitHub\microblog\app\routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Albert\Documents\GitHub\microblog\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Albert\Documents\GitHub\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\Albert\Anaconda3\envs\microblog\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\Albert\Documents\GitHub\microblog\app\templates\base.html", line 21, in block "navbar"
    <li><a href="{{ url_for('index') }}">{{ _('Home') }}</a></li>
jinja2.exceptions.UndefinedError: '_' is undefined
